-- begin CCSM_PLAN
alter table CCSM_PLAN add constraint FK_CCSM_PLAN_ON_PRODUCT foreign key (PRODUCT_ID) references CCSM_PRODUCT(ID)^
create index IDX_CCSM_PLAN_ON_PRODUCT on CCSM_PLAN (PRODUCT_ID)^
-- end CCSM_PLAN
-- begin CCSM_SUBSCRIPTION
alter table CCSM_SUBSCRIPTION add constraint FK_CCSM_SUBSCRIPTION_ON_CUSTOMER foreign key (CUSTOMER_ID) references CCSM_CUSTOMER(ID)^
alter table CCSM_SUBSCRIPTION add constraint FK_CCSM_SUBSCRIPTION_ON_PLAN foreign key (PLAN_ID) references CCSM_PLAN(ID)^
create index IDX_CCSM_SUBSCRIPTION_ON_CUSTOMER on CCSM_SUBSCRIPTION (CUSTOMER_ID)^
create index IDX_CCSM_SUBSCRIPTION_ON_PLAN on CCSM_SUBSCRIPTION (PLAN_ID)^
-- end CCSM_SUBSCRIPTION
