alter table CCSM_SUBSCRIPTION add constraint FK_CCSM_SUBSCRIPTION_ON_CUSTOMER foreign key (CUSTOMER_ID) references CCSM_CUSTOMER(ID);
create index IDX_CCSM_SUBSCRIPTION_ON_CUSTOMER on CCSM_SUBSCRIPTION (CUSTOMER_ID);
