-- begin CCSM_CUSTOMER
alter table CCSM_CUSTOMER add constraint FK_CCSM_CUSTOMER_ON_TENANT foreign key (TENANT_ID) references CUBASDBMT_TENANT(ID)^
create index IDX_CCSM_CUSTOMER_ON_TENANT on CCSM_CUSTOMER (TENANT_ID)^
-- end CCSM_CUSTOMER
-- begin CCSM_SUBSCRIPTION
alter table CCSM_SUBSCRIPTION add constraint FK_CCSM_SUBSCRIPTION_ON_CUSTOMER foreign key (CUSTOMER_ID) references CCSM_CUSTOMER(ID)^
alter table CCSM_SUBSCRIPTION add constraint FK_CCSM_SUBSCRIPTION_ON_PLAN foreign key (PLAN_ID) references CCSM_PLAN(ID)^
create index IDX_CCSM_SUBSCRIPTION_ON_CUSTOMER on CCSM_SUBSCRIPTION (CUSTOMER_ID)^
create index IDX_CCSM_SUBSCRIPTION_ON_PLAN on CCSM_SUBSCRIPTION (PLAN_ID)^
-- end CCSM_SUBSCRIPTION
-- begin CCSM_PLAN
alter table CCSM_PLAN add constraint FK_CCSM_PLAN_ON_PRODUCT foreign key (PRODUCT_ID) references CCSM_PRODUCT(ID)^
create index IDX_CCSM_PLAN_ON_PRODUCT on CCSM_PLAN (PRODUCT_ID)^
-- end CCSM_PLAN
-- begin CCSM_WAITINGLIST
alter table CCSM_WAITINGLIST add constraint FK_CCSM_WAITINGLIST_ON_ANIMAL foreign key (ANIMAL_ID) references CCSM_ANIMAL(ID)^
alter table CCSM_WAITINGLIST add constraint FK_CCSM_WAITINGLIST_ON_CONTACT foreign key (CONTACT_ID) references CCSM_CONTACT(ID)^
create index IDX_CCSM_WAITINGLIST_ON_ANIMAL on CCSM_WAITINGLIST (ANIMAL_ID)^
create index IDX_CCSM_WAITINGLIST_ON_CONTACT on CCSM_WAITINGLIST (CONTACT_ID)^
-- end CCSM_WAITINGLIST
