alter table CCSM_WAITINGLIST add constraint FK_CCSM_WAITINGLIST_ON_ANIMAL foreign key (ANIMAL_ID) references CCSM_ANIMAL(ID);
alter table CCSM_WAITINGLIST add constraint FK_CCSM_WAITINGLIST_ON_CONTACT foreign key (CONTACT_ID) references CCSM_CONTACT(ID);
create index IDX_CCSM_WAITINGLIST_ON_ANIMAL on CCSM_WAITINGLIST (ANIMAL_ID);
create index IDX_CCSM_WAITINGLIST_ON_CONTACT on CCSM_WAITINGLIST (CONTACT_ID);
